server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_video?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: v$pVhSYQ#vR0qfoA
  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

mybatis:
  config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.lsq.search.entity
  mapper-locations: classpath:mapping/*.xml









  ## File Storage Properties
  # All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: C:\OwnProject\videoSave




